name: Build Yareustrap Executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Publish App
      run: dotnet publish Yareustrap/Yareustrap.csproj --configuration Release --runtime win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishReadyToRun=true --output ./build

    - name: Upload Finished EXE
      uses: actions/upload-artifact@v4
      with:
        name: Yareustrap-Build
        path: ./build/